name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAJOR_V: 0
  MINOR_V: 0
  PATCH_V: 1

permissions:
  contents: write
  packages: write

jobs:
  execute-lint:
    permissions:
      contents: read
      statuses: write
      pull-requests: read
    uses: fruetalo182/github-workflows-templates/.github/workflows/linter-java.yaml@main
    secrets: inherit

  build-push-ghcr:
    needs: execute-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests
      run: mvn test

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:v${{ env.MAJOR_V }}.${{ env.MINOR_V }}.${{ env.PATCH_V }}-${{ github.run_number }}

    - name: Create Tag
      run: |
        git tag v${{ env.MAJOR_V }}.${{ env.MINOR_V }}.${{ env.PATCH_V }}
        git push origin v${{ env.MAJOR_V }}.${{ env.MINOR_V }}.${{ env.PATCH_V }}

    - name: Release .jar artifact
      uses: softprops/action-gh-release@v2
      with:
        files: target/java-web-app-v${{ env.MAJOR_V }}.${{ env.MINOR_V }}.${{ env.PATCH_V }}.jar